### ISSUE TITLE
Need to Keep Scan History

### ISSUE THREAD

**Issue by theshades** [ShadeySecurity/AssetInventory#6]
We now need to keep a results history of all scans which where ran.

**Comment by JKauff** [comment]
Tagging onto this, this will require a redesign of the database structure. (see: First Normal Form)

My back-of-napkin design:
auditexecute table can stay the same, just add scan end time as well as start time.
 - Reading the web2py docs, apparently record entries are automatically assigned autoincremented ids.  We will use this to tie the tables together (NOT the user-supplied identification field), but I'm not sure how to access it.

'hosts' table maintains data from the latest scan per host. 'last_scan' is the id mentioned above.
`mac [string] | vendor [string] | ip [string] | os [string] | hostname [string] | netbios [string] | last_scan [int]`

'ports' table holds per-port data from all scans for all hosts. 'scan' is the associated scan id from the 'auditexecute' table.
`scan [int] | mac [string] | port [int] | protocol [string] | state [string] | name [string] | product [string] | info [string] | tunnel [string]`

Other data should likely be in its own table as well. eg:
vulnerabilities
`mac [string] | cve [string] | name [string] | description [string] | severity [string] | scan [int]`
